/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jiiahhhh
 */
public class NewJFrame extends javax.swing.JFrame {
    
    DefaultTableModel tabelModel;

    String judul;
    String version;
    String pembayaran;
    String subscription="";
    String detail;
    String password;
    int totalHarga = 0;    
    int hargaGame = 0;
    int hargaEA, hargaXbox, hargaPS = 0;
    int hargaSub = 0;
    int biayaAdmin = 0;

    
    public NewJFrame(String msg, String pass) {
        initComponents();
        tvName.setText(msg);
        password = pass;
        NewJInternalFrame1 frame1 = new NewJInternalFrame1();
        this.jDesktopPane1.add(frame1);
        DaftarHarga frame2 = new DaftarHarga();
        this.DesktopPane2.add(frame2);
        frame1.show();
        frame2.show();
        String [] judul = {"Judul Game", "Versi", "Subscription", "Sistem Pembayaran", "Detail", "Total Harga"};
        tabelModel = new DefaultTableModel(judul, 0);
        tabel.setModel(tabelModel);
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        edtJudulGame = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboVersi = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        cbEA = new javax.swing.JCheckBox();
        cbXbox = new javax.swing.JCheckBox();
        cbPS = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        rbSteam = new javax.swing.JRadioButton();
        rbDebit = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailPesanan = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        detailPesanan1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        btnKeluar = new javax.swing.JButton();
        btnBersihkan = new javax.swing.JButton();
        btnProses = new javax.swing.JButton();
        tvName = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        DesktopPane2 = new javax.swing.JDesktopPane();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Orbitron", 1, 14)); // NOI18N
        jLabel2.setText("ROAD TO SUMMER SALE!");

        edtJudulGame.setText("Masukkan Judul Game");
        edtJudulGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtJudulGameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Judul Game");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Versi");

        comboVersi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Standard Edition", "Definitive Edition", "Legendary Edition", "Collector's Edition" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Subscription");

        cbEA.setText("EA Play");
        cbEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEAActionPerformed(evt);
            }
        });

        cbXbox.setText("Xbox Game Pass");
        cbXbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbXboxActionPerformed(evt);
            }
        });

        cbPS.setText("PlayStation Plus");
        cbPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPSActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Sistem Pembayaran");

        buttonGroup1.add(rbSteam);
        rbSteam.setText("Steam Wallet");
        rbSteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSteamActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbDebit);
        rbDebit.setText("Debit / Credit");
        rbDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDebitActionPerformed(evt);
            }
        });

        detailPesanan.setColumns(20);
        detailPesanan.setRows(5);
        detailPesanan.setText("Detail Pesanan");
        jScrollPane1.setViewportView(detailPesanan);

        detailPesanan1.setColumns(20);
        detailPesanan1.setRows(5);
        detailPesanan1.setText("Detail Pesanan");
        jScrollPane4.setViewportView(detailPesanan1);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Judul", "Versi", "Subscription", "Sistem Pembayaran", "Detail", "Total Harga"
            }
        ));
        jScrollPane2.setViewportView(tabel);

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Judul", "Versi", "Subscription", "Sistem Pembayaran", "Detail", "Total Harga"
            }
        ));
        jScrollPane5.setViewportView(tabel1);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnBersihkan.setText("Bersihkan");
        btnBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihkanActionPerformed(evt);
            }
        });

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        tvName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tvName.setText("Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(comboVersi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cbPS)
                            .addComponent(cbXbox)
                            .addComponent(cbEA)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbDebit)
                                    .addComponent(rbSteam)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tvName)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnProses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBersihkan)))
                                .addGap(66, 66, 66))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtJudulGame, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(54, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(edtJudulGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboVersi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbSteam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbDebit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tvName)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(btnBersihkan))
                                    .addComponent(btnProses))
                                .addGap(14, 14, 14)
                                .addComponent(btnKeluar)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbXbox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPS)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 717, -1));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 750, 500));

        javax.swing.GroupLayout DesktopPane2Layout = new javax.swing.GroupLayout(DesktopPane2);
        DesktopPane2.setLayout(DesktopPane2Layout);
        DesktopPane2Layout.setHorizontalGroup(
            DesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        DesktopPane2Layout.setVerticalGroup(
            DesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        getContentPane().add(DesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 750, 220));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 770));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Daftar Game");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Data Diri");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bantuan");

        jMenuItem3.setText("Password?");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tentang");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Aplikasi");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int jawab = JOptionPane.showOptionDialog(this, 
                        "Ingin Keluar?", 
                        "Keluar", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Terima Kasih sudah Berbelanja di Game_Station");
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void rbSteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSteamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSteamActionPerformed

    private void cbEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEAActionPerformed
         if(cbEA.isSelected()){
            subscription = subscription + "EA Play" + ",";
            hargaEA = 40000;
        } else {
            subscription = "";
            hargaEA = 0;
        }
    }//GEN-LAST:event_cbEAActionPerformed

    private void edtJudulGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtJudulGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtJudulGameActionPerformed

    private void rbDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDebitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDebitActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        if (rbSteam.isSelected() || rbDebit.isSelected()){
            String input = JOptionPane.showInputDialog("Masukkan Password: ");
            if (input.equals(password)){
                judul = edtJudulGame.getText();
                detail = detailPesanan.getText();

                if(comboVersi.getSelectedItem() == "Standard Edition"){
                    version = "Standard Edition";
                    hargaGame = 100000;
                } else if (comboVersi.getSelectedItem() == "Definitive Edition"){
                    version = "Definitive Edition";
                    hargaGame = 200000;
                } else if (comboVersi.getSelectedItem() == "Legendary Edition") {
                    version = "Legendary Edition";
                    hargaGame = 500000;
                } else if (comboVersi.getSelectedItem() == "Collector's Edition") {
                    version = "Collector's Edition";
                    hargaGame = 1000000;
                }

                if(rbSteam.isSelected()){
                    pembayaran = "Steam Wallet";
                    biayaAdmin = 2000;
                } else if (rbDebit.isSelected()) {
                    pembayaran = "Debit/Credit Card";
                    biayaAdmin = 3000;
                } else {
                    pembayaran = "";
                    biayaAdmin = 0;
                } 

                hargaSub = hargaEA + hargaXbox + hargaPS;
                totalHarga = hargaGame + hargaSub + biayaAdmin;

                Object[] Data = {judul, version, subscription, pembayaran, detail, totalHarga};
                tabelModel.addRow(Data);

                try{
                    Connection cn;
                    cn = DriverManager.getConnection("jdbc:mysql://localhost/tugasbasisdata","root", "");

                    cn.createStatement().executeUpdate("insert into game values"+"('"+judul+"','"+version+"','"+subscription+"','"+pembayaran+"','"+detail+"','"+totalHarga+"')");
                    JOptionPane.showMessageDialog(this, "Pesanan Anda Telah Diproses");
                    tampilkan();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Ada Data yang Tidak Terisi");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Password salah");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Harap memilih Sistem Pembayaran");
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihkanActionPerformed
        edtJudulGame.setText("");
        comboVersi.setSelectedItem("Standard Edition");
        cbXbox.setSelected(false);
        cbEA.setSelected(false);
        cbPS.setSelected(false);
        rbSteam.setSelected(false);
        rbDebit.setSelected(false);
        detailPesanan.setText("");
    }//GEN-LAST:event_btnBersihkanActionPerformed

    private void cbXboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbXboxActionPerformed
        if(cbXbox.isSelected()){
            subscription = subscription + "Xbox GamePass" + ",";
            hargaXbox = 60000;
            hargaXbox = 0;
        } else {
            subscription = "";
        }
    }//GEN-LAST:event_cbXboxActionPerformed

    private void cbPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPSActionPerformed
        if(cbPS.isSelected()){
            subscription = subscription + "PlayStation Plus" + ",";
            hargaPS = 80000;
        } else {
            subscription = "";
            hargaPS = 0;
        }
    }//GEN-LAST:event_cbPSActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        NewJInternalFrame1 frame1;
        frame1 = new NewJInternalFrame1();
        this.jDesktopPane1.add(frame1);
        frame1.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(this, "Nama Lengkap: "+ tvName.getText());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String input = JOptionPane.showInputDialog("Masukkan Nama Lengkap");
        if (input.equals(tvName.getText())){
            JOptionPane.showMessageDialog(this, "Password: " + password);
        } else {
            JOptionPane.showMessageDialog(this, "Maaf data tidak sesuai");
        }
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JOptionPane.showMessageDialog(this, "Pahrul - D121191020");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
        
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane2;
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnProses;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbEA;
    private javax.swing.JCheckBox cbPS;
    private javax.swing.JCheckBox cbXbox;
    private javax.swing.JComboBox<String> comboVersi;
    private javax.swing.JTextArea detailPesanan;
    private javax.swing.JTextArea detailPesanan1;
    private javax.swing.JTextField edtJudulGame;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton rbDebit;
    private javax.swing.JRadioButton rbSteam;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tabel1;
    private javax.swing.JLabel tvName;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
        int row = tabel.getRowCount();
        for(int a=0;a<row;a++){
            tabelModel.removeRow(0);
        }
        try{
            Connection cn;
            cn = DriverManager.getConnection("jdbc:mysql://localhost/tugasbasisdata","root", "");
            
            ResultSet rs = cn.createStatement().executeQuery("SELECT *FROM game");
            
            while(rs.next()){
                String data[]={rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)};
                tabelModel.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
}