/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author Jiiahhhh
 */
public class NewJInternalFrame1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame1
     */
    public NewJInternalFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(750, 500));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Animal Crossing: New Horizons", "Social Simulation", "Nintendo", "90"},
                {"Assassin's Creed Odyssey", "Action role-playing", "Ubisoft", "87"},
                {"Bayonetta 2", "Action", "PlatinumGames", "92"},
                {"Bloodborne", "Action role-playing", "FromSoftware", "92"},
                {"Celeste", "Platform", "Matt Makes Games", "94"},
                {"Control", "Action-adventure", "Remedy Entertainment", "83"},
                {"Dark Souls II", "Action role-playing", "FromSoftware", "91"},
                {"Death Stranding", "Action", "Kojima Productions", "86"},
                {"Doom", "First-person shooter", "id Software", "87"},
                {"Doom Eternal", "First-person shooter", "id Software", "88"},
                {"Dragon Age: Inquisition", "Action role-playing", "BioWare", "89"},
                {"Fallout 4", "Action role-playing", "Bethesda Game Studios", "87"},
                {"Final Fantasy VII Remake", "Action role-playing", "Square Enix", "87"},
                {"Ghost of Tsushima", "Stealth", "Sucker Punch Productions", "83"},
                {"God of War", "Action-adventure", "Santa Monica Studio", "94"},
                {"Hades", "Roguelike", "Supergiant Games", "93"},
                {"Hearthstone", "Card Game", "Blizzard Entertainment", "93"},
                {"Horizon Zero Dawn", "Action role-playing", "Guerilla Games", "89"},
                {"Inside", "Platform", "Playdead", "93"},
                {"Marvel's Spider-Man", "Action-adventure", "Insomniac Games", "87"},
                {"Metal Gear Solid V: The Phantom Pain", "Stealth", "Kojima Productions", "95"},
                {"Middle-earth: Shadow of Mordor", "Action-adventure", "Monolith Productions", "87"},
                {"Monster Hunter: World", "Action role-playing", "Capcom", "90"},
                {"Overwatch", "First-person shooter", "Blizzard Entertainment", "91"},
                {"Persona 5", "Role-playing", "Atlus", "93"},
                {"PlayerUnknown's Battlegrounds", "Battle Royale", "PUBG Corporation", "86"},
                {"Red Dead Redemption 2", "Action-adventure", "Rockstar Games", "97"},
                {"Resident Evil 2", "Survival", "Capcom", "91"},
                {"Sekiro: Shadows Die Twice", "Action-adventure", "FromSoftware", "91"},
                {"Super Mario Maker", "Platform", "Nintendo", "88"},
                {"Super Mario Odyssey", "Platform", "Nintendo", "97"},
                {"Super Smash Bros. Ultimate", "Fighting", "Bandai Namco", "93"},
                {"The Last of Us Part II", "Action-adventure", "Naughty Dog", "93"},
                {"The Legend of Zelda: Breath of the Wild", "Action-adventure", "Nintendo", "97"},
                {"The Outer Worlds", "Action role-playing", "Obsidian Entertainment", "76"},
                {"The Witcher 3: Wild Hunt", "Action role-playing", "CD Projekt Red", "93"},
                {"Titanfaal 2", "First-person shooter", "Respawn Entertainment", "89"},
                {"Uncharted 4: A Thief's End", "Action-adventure", "Naughty Dog", "93"}
            },
            new String [] {
                "Judul", "Genre", "Developer", "Metascore"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setFont(new java.awt.Font("Orbitron", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DAFTAR GAME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
